### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-lucero012#1]
[ASSEMBLY.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-lucero012/files/15204827/ASSEMBLY.pdf)

**Comment by carlos0716c** [comment]
CALIFICADO DE ACUERDO A LA RÚBRICA

Partes de la infografía: 4
Coherencia y pertinencia: 4
Organización de la información: 4
Diseño y composición de la infografía: 4
Creatividad: 4
Total=20
CALIFICACIÓN=20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
